// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddAccount'](arg1, arg2, arg3, arg4, arg5);
}

export function FirstPage() {
  return window['go']['main']['App']['FirstPage']();
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
